name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install tar and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv git zip unzip tar openjdk-17-jdk

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Buildozer and Cython
        run: |
          python -m pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Initialize Buildozer
        run: |
          buildozer init
          echo "requirements = python3,kivy" >> buildozer.spec
          echo "package.name = HelloKivyApp" >> buildozer.spec
          echo "package.domain = org.example" >> buildozer.spec
          echo "android.minapi = 17" >> buildozer.spec
          echo "android.api = 33" >> buildozer.spec
          echo "android.arch = arm64-v8a,armeabi-v7a" >> buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-kivy-apk
          path: bin/*.apk
